name: Build Action
on:
  push:
    branches:
      - main

jobs:
  build:
    name: building project
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: starting using nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: build
        run: |
          echo "=====> Installing dependencies"
          npm install
          echo "=====> Building project"
          npm run build_prod
          echo "=====> Let's ZIP it!"
          zip -j -r phaser_dude_loader_demo.zip build
          echo "=====> DONE!"

      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GH_CREDENTIALS }}
          tag_prefix: ""

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_CREDENTIALS }}
          tag: ${{ steps.generate_release_tag.outputs.release_tag }}
          artifacts: phaser_dude_loader_demo.zip
